name: ai_music
description: 一个在线听歌的桌面APP，参考QQ音乐、酷我音乐的布局和设计
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audio_service: ^0.18.8
  just_audio: ^0.9.40  # 更新到支持 Windows 的版本
  just_audio_windows: ^0.2.0  # Windows 平台支持
  audio_session: ^0.1.19  # 音频会话管理
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  rxdart: ^0.27.7  # 响应式编程库
  logger: ^2.0.2+1  # 专业日志记录组件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

